---
name: Deploy on server via copy from GitHub
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER:  ${{ secrets.SSH_USER }}
          TARGET: ${{ vars.REMOTE_DIR_DEPLOY }}
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            cd ${{ vars.REMOTE_DIR_DEPLOY }}
            sudo docker stop user-service-masterskaya-container
            sudo docker rm -f user-service-masterskaya-container
            sudo docker-compose up -d
          SCRIPT_BEFORE_REQUIRED: true

