name: Deploy JavaApp via Github Actions without Docker containers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B package -DskipTests
    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.PRIVATE_KEY }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} << EOF
        mkdir -p /home/java-team3-1/nikvitya/app
        scp -p ./user-service/target/user-service-1.0.0.jar /home/java-team3-1/nikvitya/app
        cd /home/java-team3-1/nikvitya/app && nohup java -jar user-service-1.0.0.jar > /home/java-team3-1/nikvita/app/app.log 2>&1 &
        exit 0
        EOF
