name: Deploy JavaApp via Github Actions without Docker containers

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml
        mkdir staging
        cp user-service/target/*.jar staging
    - name: Deploy to Server
      if: steps.build.outcome == 'success'
      run: |
       ssh -o StrictHostKeyChecking=no -i ${{ secrets.PRIVATE_KEY }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} "
        mkdir -p /home/java-team3-1/nikvitya/appNoDocker
        scp -p staging/user-service-*.jar ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:/home/java-team3-1/nikvitya/appNoDocker/
        cd /home/java-team3-1/nikvitya/appNoDocker && nohup java -jar user-service-*.jar > /home/java-team3-1/nikvitya/appNoDocker/app.log 2>&1 &
    "
