name: Deploy JavaApp via Github Actions without Docker containers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B package -DskipTests
    - name: Deploy to Server
      run: |
        ssh -i ${{ secrets.PRIVATE_KEY }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} << EOF
          mkdir -p /home/java-team3-1/app
          # Critically important: Check if the JAR file already exists
          if [[ ! -f /home/java-team3-1/app/user-service-*.jar ]]; then
            # Copy the JAR to the server
            scp -p ./target/user-service-*.jar ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:/home/java-team3-1/app/
          fi
          # IMPORTANT: Use the correct JAR filename.
          cd /home/java-team3-1/app &&
          nohup java -jar user-service-1.0.0.jar > /home/java-team3-1/app/app.log 2>&1 &
          echo "Deployment complete."
        EOF
