# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven
    - name: Checkstyle
      uses: actions/checkout@v4
      with:
        config_file: checkstyle.xml # Путь к вашему checkstyle.xml
        #Можно изменить уровень серьезности ошибки, по умолчанию это ошибка
        # severity: warning
    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml
        mkdir staging
        cp user-service/target/*.jar staging
    - uses: actions/upload-artifact@v4
      with:
         name: Package
         path: staging

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive

